## Basic Data types and converting to 32 BIT

In [3]:
import torch 

tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1, 2], [3,4]])
tensor3d = torch.tensor([[[1, 2], [3,4]], [[5,6], [7,8]]])



In [5]:
#better to convert to 32 bit int to save memory
print(tensor1d.dtype)


torch.int64


In [ ]:
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)
print(floatvec)

#tensor([1., 2., 3.]) make it a float 

torch.float32
tensor([1., 2., 3.])


## Common Operations 

In [ ]:
import torch 

tensor2d = torch.tensor([[1,2,3], [4,5,6]])

print(tensor2d)
print(tensor2d.shape) #2 rows, 3 columns. 

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [10]:
#able to directly reshape
tensor2d_reshaped = tensor2d.reshape(3, 2)
print(tensor2d_reshaped)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [11]:
#also transpose (flipping across diagonals)
tensor2d_transposed = tensor2d.T
print(tensor2d_transposed)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [14]:
#multiply matrices 
tensor2d_multiplied = tensor2d.matmul(tensor2d_transposed)
print(tensor2d_multiplied)

#also can do with @ 
tensor2d_multiplied_2 = tensor2d @ tensor2d_transposed
print(tensor2d_multiplied_2)



tensor([[14, 32],
        [32, 77]])
tensor([[14, 32],
        [32, 77]])
