computing the gradient using autograd 

In [ ]:
import torch.nn.functional as F 
from torch.autograd import grad 
import torch

In [ ]:
y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True) #tells PyTorch to track this tensor for gradient computation
b = torch.tensor([0.0], requires_grad=True) #same as above

z = w1 * x1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

#compute gradients
grad_L_w1 = grad(loss,w1,retain_graph=True)#how much does w1 affect the loss?
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)
#printed shows how much w1 and b affect the loss 
#negative is increase w1 and b, loss goes down.
#positive is increase w1 and b, loss goes up.
#(tensor([-0.0898]),)
#(tensor([-0.0817]),)
#slight decrease in w1 and b would decrease the loss.

(tensor([-0.0898]),)
(tensor([-0.0817]),)


using .backward on loss will compute gradient of all leaf nodes and stored with .grad attirbute

In [3]:
loss.backward() #compute gradients for all tensors with requires_grad=True
print(w1.grad) #same as grad_L_w1
print(b.grad) #same as grad_L_b

tensor([-0.0898])
tensor([-0.0817])
